application: teardownthispaywall
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /thanks
  static_files: thanks.html
  upload: thanks.html

- url: /.*
  script: petition.app

libraries:
- name: jinja2
  version: latest
